version: '1.0'
services:
  postgres_db:
    image: postgres:latest
    ports:
      - '5432:5432'
    networks:
      - bridge
    volumes:
      - "el_db:/var/lib/postgresql/data"

    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
  el_code:
    build: .
    networks:
      - bridge
    volumes:
      #- el_task: /app/code
networks:
  bridge:

volumes:
  el_db:
